### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by awesominat** [awesominat/stonks#13]
contents:
1. what is the project about (general description)
2. what problem it attempts to solve
3. some use cases
4. set up instructions
5. picture examples of it working

**not** all of them should be created at once. PRs created to resolve this issue can tackle one of the contents, not necessarily all. however, the readme is an important part of the project

**Comment by quiz3** [comment]
I can fill in some of the README details from our specifications Google Doc.

**Comment by quiz3** [comment]
Updated Issue:

1. ~~what is the project about (general description)~~
    &rarr; *Is there a sufficient amount here, or should we add the more detailed specification?*
2. ~~what problem it attempts to solve~~
3. ~~some use cases~~
4. set up instructions
5. picture examples of it working

Every task need not be completed at once. PRs created to resolve this issue can tackle individual tasks. 

In any case, progress is welcome because the README is an important part of the project.
